from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from frontend.controllers.search_controller import SearchConfig, execute_search
from frontend.ui.renderers import render_context_sources


RAG_RETRIEVER_MAP = {
    "BERT": "bert",
    "BM25": "bm25",
    "TF-IDF": "tfidf",
    "Parallel Hybrid": "parallel",
}


def build_context(results: list[dict[str, Any]], context_docs: int, max_context_chars: int) -> str:
    """Build the textual context sent to the generator from retrieved documents."""
    chunks: list[str] = []
    used = 0

    for i, item in enumerate(results[: int(context_docs)], start=1):
        title = (item.get("title") or "").strip()
        abstract = (item.get("abstract") or "").strip()
        raw_text = (item.get("raw_text") or "").strip()
        doc_id = item.get("doc_id")
        score = item.get("score")

        text = raw_text or abstract
        chunk = (
            f"[Source {i}]\n"
            f"Doc ID: {doc_id}\n"
            f"Score: {score}\n"
            f"Title: {title}\n"
            f"Text: {text}\n"
        )

        remaining = int(max_context_chars) - used
        if remaining <= 0:
            break

        chunk = chunk[:remaining]
        used += len(chunk)
        chunks.append(chunk)

    return "\n---\n".join(chunks)


def build_rag_prompt(question: str, context: str) -> str:
    return f"""You are a biomedical question-answering assistant.

Answer the user's question using ONLY the retrieved MEDLINE context below.

Rules:
- Do not use outside knowledge.
- If the context is insufficient, say: "The retrieved documents do not provide enough evidence."
- Mention biomedical entities only if they appear in the context.
- Keep the answer concise and factual.
- At the end, include a short "Sources used" line using the source numbers.

Retrieved MEDLINE context:
{context}

User question:
{question}

Answer:
"""


def _generate_with_huggingface(prompt: str, model_name: str, max_new_tokens: int) -> str:
    try:
        from transformers import pipeline
    except Exception as exc:
        return (
            "Local HuggingFace generation is not available because transformers could not be imported.\n"
            f"Reason: {exc}\n\n"
            "The RAG prompt is shown below.\n\n"
            + prompt
        )

    try:
        generator = pipeline("text2text-generation", model=model_name)
        result = generator(prompt, max_new_tokens=int(max_new_tokens), do_sample=False)
        return str(result[0].get("generated_text", "")).strip()
    except Exception as exc:
        return (
            "Local HuggingFace generation failed. Retrieval and prompt construction still worked.\n"
            f"Reason: {exc}\n\n"
            "Prompt used:\n\n" + prompt
        )


def _generate_with_gemini(
    prompt: str,
    api_key: str | None,
    model_name: str,
    temperature: float,
    max_output_tokens: int,
) -> str:
    api_key = (api_key or "").strip() or os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        return (
            "Gemini generation was requested, but no API key was provided.\n"
            "Put the key in the UI field or set the GEMINI_API_KEY environment variable.\n\n"
            "The RAG prompt is shown below.\n\n" + prompt
        )

    try:
        from google import genai
        from google.genai import types
    except Exception as exc:
        return (
            "Gemini generation is not available because google-genai could not be imported.\n"
            f"Reason: {exc}\n\n"
            "Install it with: python -m pip install google-genai\n\n"
            "The RAG prompt is shown below.\n\n" + prompt
        )

    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model=(model_name or "gemini-1.5-flash").strip(),
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=float(temperature),
                max_output_tokens=int(max_output_tokens),
            ),
        )
        return (response.text or "No answer was generated by Gemini.").strip()
    except Exception as exc:
        return (
            "Gemini generation failed. Retrieval and prompt construction still worked.\n"
            f"Reason: {exc}\n\n"
            "Prompt used:\n\n" + prompt
        )


def _build_search_config_for_rag(
    question: str,
    retriever_model: str,
    retrieve_k: int,
    bm25_k1: float,
    bm25_b: float,
    index_path: str,
    db_path: str,
    bert_index_dir: str,
    bert_model_name: str,
    word2vec_index_dir: str,
    enable_refinement: bool,
    refinement_method: str,
    prf_feedback_docs: int,
    max_prf_terms: int,
    max_expansion_terms: int,
    word2vec_topn: int,
    min_word2vec_similarity: float,
    original_term_weight: int,
) -> SearchConfig:
    model = RAG_RETRIEVER_MAP.get(retriever_model, "bert")
    return SearchConfig(
        model=model,
        query=(question or "").strip(),
        top_k=int(retrieve_k),
        bm25_k1=float(bm25_k1),
        bm25_b=float(bm25_b),
        index_path=index_path,
        db_path=db_path,
        bert_index_dir=bert_index_dir,
        bert_model_name=bert_model_name,
        word2vec_index_dir=word2vec_index_dir,
        parallel_models=("bm25", "bert"),
        per_model_k=int(retrieve_k),
        enable_refinement=bool(enable_refinement),
        refinement_method=refinement_method,
        refinement_prf_feedback_docs=int(prf_feedback_docs),
        refinement_max_prf_terms=int(max_prf_terms),
        refinement_max_expansion_terms=int(max_expansion_terms),
        refinement_word2vec_topn=int(word2vec_topn),
        refinement_min_word2vec_similarity=float(min_word2vec_similarity),
        refinement_original_term_weight=int(original_term_weight),
    )


def run_rag(
    question: str,
    retriever_model: str,
    retrieve_k: int,
    bm25_k1: float,
    bm25_b: float,
    context_docs: int,
    max_context_chars: int,
    answer_mode: str,
    hf_model_name: str,
    gemini_model_name: str,
    gemini_api_key: str,
    gemini_temperature: float,
    max_new_tokens: int,
    index_path: str,
    db_path: str,
    bert_index_dir: str,
    bert_model_name: str,
    word2vec_index_dir: str,
    enable_refinement: bool,
    refinement_method: str,
    prf_feedback_docs: int,
    max_prf_terms: int,
    max_expansion_terms: int,
    word2vec_topn: int,
    min_word2vec_similarity: float,
    original_term_weight: int,
) -> tuple[str, str, str, str]:
    if not (question or "").strip():
        raise ValueError("Question is required for RAG.")

    started = time.time()
    config = _build_search_config_for_rag(
        question=question,
        retriever_model=retriever_model,
        retrieve_k=retrieve_k,
        bm25_k1=bm25_k1,
        bm25_b=bm25_b,
        index_path=index_path,
        db_path=db_path,
        bert_index_dir=bert_index_dir,
        bert_model_name=bert_model_name,
        word2vec_index_dir=word2vec_index_dir,
        enable_refinement=enable_refinement,
        refinement_method=refinement_method,
        prf_feedback_docs=prf_feedback_docs,
        max_prf_terms=max_prf_terms,
        max_expansion_terms=max_expansion_terms,
        word2vec_topn=word2vec_topn,
        min_word2vec_similarity=min_word2vec_similarity,
        original_term_weight=original_term_weight,
    )

    search_output = execute_search(config)
    results = search_output.get("results") or []
    context = build_context(results, int(context_docs), int(max_context_chars))
    prompt = build_rag_prompt(question, context)

    mode = (answer_mode or "Build prompt only").strip()
    if mode == "Gemini API":
        answer = _generate_with_gemini(
            prompt=prompt,
            api_key=gemini_api_key,
            model_name=gemini_model_name,
            temperature=float(gemini_temperature),
            max_output_tokens=int(max_new_tokens),
        )
    elif mode == "Local HuggingFace":
        answer = _generate_with_huggingface(prompt, hf_model_name, int(max_new_tokens))
    else:
        answer = prompt

    rag_output = {
        "question": question,
        "answer_mode": mode,
        "retriever": retriever_model,
        "retrieve_k": int(retrieve_k),
        "bm25_parameters": {
            "k1": float(bm25_k1),
            "b": float(bm25_b),
        },
        "context_docs": int(context_docs),
        "max_context_chars": int(max_context_chars),
        "answer": answer,
        "context": context,
        "prompt": prompt,
        "sources": results[: int(context_docs)],
        "search_output": search_output,
        "rag_total_time_seconds": time.time() - started,
    }

    sources_html = render_context_sources(results, max_docs=int(context_docs))
    return answer, context, sources_html, json.dumps(rag_output, ensure_ascii=False, indent=2, default=str)
