from __future__ import annotations

from src.rag.config import (
    GEMINI_API_KEY,
    GEMINI_MAX_OUTPUT_TOKENS,
    GEMINI_MODEL_NAME,
    GEMINI_TEMPERATURE,
)


class GeminiGenerator:
    def __init__(
        self,
        api_key: str | None = None,
        model_name: str | None = None,
        temperature: float | None = None,
        max_output_tokens: int | None = None,
    ):
        api_key = (api_key or GEMINI_API_KEY or "").strip()
        if not api_key:
            raise RuntimeError(
                "Gemini API key is missing. Pass api_key to GeminiGenerator, "
                "set GEMINI_API_KEY, or enter it in the UI."
            )

        try:
            from google import genai
        except Exception as exc:
            raise RuntimeError(
                "google-genai is not installed. Install it with: python -m pip install google-genai"
            ) from exc

        self._genai = genai
        self.client = genai.Client(api_key=api_key)
        self.model_name = model_name or GEMINI_MODEL_NAME
        self.temperature = GEMINI_TEMPERATURE if temperature is None else float(temperature)
        self.max_output_tokens = GEMINI_MAX_OUTPUT_TOKENS if max_output_tokens is None else int(max_output_tokens)

    def generate(self, prompt: str, max_new_tokens: int | None = None) -> str:
        from google.genai import types

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=self.temperature,
                max_output_tokens=int(max_new_tokens or self.max_output_tokens),
            ),
        )

        return (response.text or "No answer was generated by Gemini.").strip()
